---

mrs_uav_controllers:

  controller_module:

    nmpc:

      solver:

        ac_num_iter: 20 # [-]
        ac_horizon: 0.8 # [s]
        ac_time_steps: [0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.04,0.04,0.04,0.04,0.04,0.08,0.08,0.08,0.08,0.08]

        integral_relaxation_index: 3
        enable_integral_relaxation: true

      costs:

        Q_position_xy: 100.0
        Q_position_z: 100.0
        Q_rotation_xy: 26
        Q_rotation_z: 20
        Q_thrust: 0.2
        Q_velocity: 2.0
        Q_int: 0.02
        Q_omega: 2.0

        R_col_thrust: 0.2
        R_ome_in: 12


      optional:

        verbose: False
        warn_too_high_body_rates: False
        warn_body_rates: [5,5,1]
