#
## DEFINITION OF THE ARENA
#

world_origin:

  units: "LATLON" # {"UTM, "LATLON"}

  origin_x: 47.397743
  origin_y: 8.545594

safety_area:

  enabled: true

  horizontal:

    # the frame of reference in which the points are expressed
    frame_name: "world_origin"

    # convex polygon CCW
    points: [
      -50, -50,
      50,  -50,
      50,  50,
      -50, 50
    ]

  vertical:

    # the frame of reference in which the max&min z is expressed
    frame_name: "world_origin"

    max_z: 15.0
    min_z: 0.5

